- src: https://github.com/oatakan/ansible-role-ec2
  version: origin/master

- src: https://github.com/oatakan/ansible-role-rhel_upgrade
  version: origin/master
  name: oatakan.rhel_upgrade

- src: https://github.com/oatakan/ansible-role-rhn
  version: origin/master
  name: oatakan.rhn

- src: https://github.com/oatakan/ansible-role-vmware
  version: origin/master